"""Auto Seam UV Equalizer Blender add-on."""

from __future__ import annotations

bl_info = {
    "name": "Auto Seam UV Equalizer",
    "author": "Generated by Codex",
    "version": (0, 8, 0),
    "blender": (5, 1, 2),
    "location": "View3D > Sidebar > Auto UV",
    "description": "Automatically mark seams and unwrap selected mesh objects.",
    "category": "UV",
}

import bpy  # noqa: E402
from bpy.props import PointerProperty  # noqa: E402

from . import operators, operators_seam, operators_symmetry, operators_validation, properties, translations, ui

CLASSES = (
    properties.AUTOSEAMUV_PG_settings,
    operators.AUTOSEAMUV_OT_mark_selected_region_boundary,
    operators.AUTOSEAMUV_OT_analyze_seams,
    operators.AUTOSEAMUV_OT_generate_seams,
    operators.AUTOSEAMUV_OT_detect_ring_strip,
    operators.AUTOSEAMUV_OT_unwrap_ring_strip,
    operators.AUTOSEAMUV_OT_mark_only,
    operators.AUTOSEAMUV_OT_unwrap_only,
    operators.AUTOSEAMUV_OT_unwrap_selected_faces,
    operators.AUTOSEAMUV_OT_weighted_island_layout,
    operators.AUTOSEAMUV_OT_shared_weighted_atlas,
    operators.AUTOSEAMUV_OT_pack_islands,
    operators.AUTOSEAMUV_OT_auto_unwrap_pack,
    operators.AUTOSEAMUV_OT_mark_and_unwrap,
    operators.AUTOSEAMUV_OT_atlas_pack_selected_objects,
    operators.AUTOSEAMUV_OT_check_uv_overlap,
    operators.AUTOSEAMUV_OT_clear_uv_overlap_highlight,
    operators.AUTOSEAMUV_OT_clear_seams,
    *operators_seam.CLASSES,
    *operators_symmetry.CLASSES,
    *operators_validation.CLASSES,
    *ui.CLASSES,
)


def register() -> None:
    """Register add-on classes and scene properties."""
    for cls in CLASSES:
        bpy.utils.register_class(cls)

    bpy.types.Scene.autoseamuv_settings = PointerProperty(type=properties.AUTOSEAMUV_PG_settings)
    for scene in bpy.data.scenes:
        properties.migrate_legacy_settings(scene.autoseamuv_settings)
    translations.register()


def unregister() -> None:
    """Unregister add-on classes and scene properties."""
    translations.unregister()
    if hasattr(bpy.types.Scene, "autoseamuv_settings"):
        del bpy.types.Scene.autoseamuv_settings

    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)


if __name__ == "__main__":
    register()
