"""Auto Seam UV Equalizer Blender add-on."""

from __future__ import annotations

bl_info = {
    "name": "Auto Seam UV Equalizer",
    "author": "Generated by Codex",
    "version": (0, 8, 0),
    "blender": (5, 1, 2),
    "location": "View3D > Sidebar > Auto UV",
    "description": "Automatically mark seams and unwrap selected mesh objects.",
    "category": "UV",
}

import bpy  # noqa: E402
from bpy.props import PointerProperty  # noqa: E402

from . import operators, operators_seam, operators_symmetry, operators_validation, properties, translations, ui

CLASSES = (
    properties.AUTOSEAMUV_PG_settings,
    operators.AUTOSEAMUV_OT_mark_selected_region_boundary,
    operators.AUTOSEAMUV_OT_analyze_seams,
    operators.AUTOSEAMUV_OT_generate_seams,
    operators.AUTOSEAMUV_OT_detect_ring_strip,
    operators.AUTOSEAMUV_OT_unwrap_ring_strip,
    operators.AUTOSEAMUV_OT_mark_only,
    operators.AUTOSEAMUV_OT_unwrap_only,
    operators.AUTOSEAMUV_OT_unwrap_selected_faces,
    operators.AUTOSEAMUV_OT_weighted_island_layout,
    operators.AUTOSEAMUV_OT_shared_weighted_atlas,
    operators.AUTOSEAMUV_OT_pack_islands,
    operators.AUTOSEAMUV_OT_auto_unwrap_pack,
    operators.AUTOSEAMUV_OT_mark_and_unwrap,
    operators.AUTOSEAMUV_OT_atlas_pack_selected_objects,
    operators.AUTOSEAMUV_OT_check_uv_overlap,
    operators.AUTOSEAMUV_OT_clear_uv_overlap_highlight,
    operators.AUTOSEAMUV_OT_clear_seams,
    *operators_seam.CLASSES,
    *operators_symmetry.CLASSES,
    *operators_validation.CLASSES,
    *ui.CLASSES,
)

_SCENE_PROPERTY = "autoseamuv_settings"
_LIFECYCLE_KEY = "auto_seam_uv_equalizer.registration"
_GENERATION = object()
_registered_classes: list[type] = []
_translations_registered = False


def _registered_class(name: str):
    """Return Blender's registered RNA class with *name*, if one exists."""
    return getattr(bpy.types, name, None)


def _remove_scene_property() -> None:
    """Remove the RNA pointer before its PropertyGroup can be unregistered."""
    if hasattr(bpy.types.Scene, _SCENE_PROPERTY):
        delattr(bpy.types.Scene, _SCENE_PROPERTY)


def _make_cleanup(classes: tuple[type, ...], translations_are_registered: bool):
    """Capture one generation's objects so module reload cannot change them."""
    def cleanup() -> None:
        _remove_scene_property()
        if translations_are_registered:
            translations.unregister()
        for cls in reversed(classes):
            if _registered_class(cls.__name__) is cls:
                bpy.utils.unregister_class(cls)

    return cleanup


def _cleanup_previous_generation() -> None:
    """Prefer the previous generation's complete lifecycle when available."""
    previous = bpy.app.driver_namespace.get(_LIFECYCLE_KEY)
    if previous and previous.get("generation") is not _GENERATION:
        previous["cleanup"]()
        bpy.app.driver_namespace.pop(_LIFECYCLE_KEY, None)


def _validate_classes() -> None:
    if len(CLASSES) != len(set(CLASSES)):
        raise RuntimeError("Auto Seam UV Equalizer CLASSES contains duplicate class objects")
    names = [cls.__name__ for cls in CLASSES]
    if len(names) != len(set(names)):
        raise RuntimeError("Auto Seam UV Equalizer CLASSES contains duplicate class names")


def register() -> None:
    """Register add-on classes and scene properties."""
    global _registered_classes, _translations_registered

    _validate_classes()
    # The pointer owns an RNA reference to the old PropertyGroup and therefore
    # must always disappear before any stale class is unregistered.
    _remove_scene_property()
    _cleanup_previous_generation()

    # Remove a generation that predates lifecycle tracking.  bpy.types returns
    # the actual registered Python class and is safe to pass to unregister_class.
    for cls in reversed(CLASSES):
        registered = _registered_class(cls.__name__)
        if registered is not None and registered is not cls:
            bpy.utils.unregister_class(registered)

    registered_now: list[type] = []
    pointer_created = False
    translations_now = False
    try:
        for cls in CLASSES:
            if _registered_class(cls.__name__) is cls:
                continue
            bpy.utils.register_class(cls)
            registered_now.append(cls)

        setattr(
            bpy.types.Scene,
            _SCENE_PROPERTY,
            PointerProperty(type=properties.AUTOSEAMUV_PG_settings),
        )
        pointer_created = True
        for scene in bpy.data.scenes:
            properties.migrate_legacy_settings(getattr(scene, _SCENE_PROPERTY))
        translations.register()
        translations_now = True
    except Exception:
        if pointer_created:
            _remove_scene_property()
        if translations_now:
            translations.unregister()
        for cls in reversed(registered_now):
            if _registered_class(cls.__name__) is cls:
                bpy.utils.unregister_class(cls)
        _registered_classes = []
        _translations_registered = False
        bpy.app.driver_namespace.pop(_LIFECYCLE_KEY, None)
        raise

    _registered_classes = list(CLASSES)
    _translations_registered = True
    bpy.app.driver_namespace[_LIFECYCLE_KEY] = {
        "generation": _GENERATION,
        "cleanup": _make_cleanup(tuple(CLASSES), True),
    }


def unregister() -> None:
    """Unregister add-on classes and scene properties."""
    global _registered_classes, _translations_registered

    _remove_scene_property()
    state = bpy.app.driver_namespace.get(_LIFECYCLE_KEY)
    if state:
        state["cleanup"]()
        bpy.app.driver_namespace.pop(_LIFECYCLE_KEY, None)
        _translations_registered = False
    elif _translations_registered:
        translations.unregister()
        _translations_registered = False

    for cls in reversed(CLASSES):
        if _registered_class(cls.__name__) is cls:
            bpy.utils.unregister_class(cls)
    _registered_classes = []


if __name__ == "__main__":
    register()
